-- Bulk Insert Experimental Agents - Part 3 (EDUCATION, PRODUCTIVITY, BUSINESS, CAREER)
-- Run this to create experimental agents for testing Gaia routing

-- ============================================================================
-- EDUCATION AGENTS
-- ============================================================================

INSERT INTO agents (name, slug, description, domain, status, invocation_type, invocation_config)
VALUES
  ('Studying with ADHD Agent', 'adhd-study-agent', 'Builds ADHD-friendly study systems (timers, chunking, dopamine hacks).', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('ADHD Task Breakdown Agent', 'adhd-breakdown-agent', 'Breaks tasks into micro-steps suitable for ADHD workflows.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Concept Explainer', 'concept-explainer', 'Explains difficult concepts at 5 levels: child, student, college, grad, expert.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Quick Explanation Agent', 'quick-explainer', 'Gives 3-sentence explanations of any concept.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Mental Model Coach', 'mental-model-coach', 'Teaches decision-making models like Pareto, second-order thinking, OODA.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Memory Palace Builder', 'memory-palace-builder', 'Converts concepts into memory-palace style mnemonics.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Vocabulary Builder', 'vocab-builder', 'Creates personalized vocabulary lists with definitions, examples, and quizzes.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Lecture Simplifier', 'lecture-simplifier', 'Converts dense lecture transcripts into structured summaries with learning objectives.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Memory Recall Trainer', 'memory-recall-trainer', 'Generates recall exercises and spaced quizzes for studying.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Personalized Study Notes Agent', 'study-notes-agent', 'Converts lectures/readings into personalized study notes.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Flash Revision Agent', 'flash-revision-agent', 'Gives short flash revision summaries right before exams.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Exam Countdown Agent', 'exam-countdown-agent', 'Tracks exam dates and generates revision timelines.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Class Sign-Up Planner', 'class-signup-planner', 'Suggests optimal class schedules based on load and preferences.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Short Form Explainer', '3sentence-explainer', 'Explains any concept in exactly three sentences.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Study Break Timing Agent', 'studybreak-agent', 'Tells the ideal moment to take a break based on workload.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Word Definition Agent', 'word-def-agent', 'Gives simple, kid-friendly definitions.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Loss Function Explainer', 'lossfunction-agent', 'Explains ML loss functions intuitively.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Study Habit Tracker', 'study-habit-agent', 'Tracks study habits + reinforcement loops.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Study Planner', 'study-planner', 'Generates optimized study schedules using spaced repetition, deadlines, topic difficulty, and available hours.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Study Time Calculator', 'study-time-calculator', 'Computes how many hours are needed to master a topic based on difficulty, exam date, and available time.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Exam Revision Planner', 'exam-revision-planner', 'Designs detailed revision roadmaps for upcoming exams, broken into daily tasks and priority levels.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Soft Tutor', 'soft-tutor', 'A gentle, patient tutor who explains complex ideas simply and step-by-step with encouragement.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Math Tutor', 'math-tutor', 'Provides step-by-step explanations for calculus, algebra, geometry, and proofs.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Physics Tutor', 'physics-tutor', 'Explains physics concepts, solves problems, and shows derivations.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Chemistry Tutor', 'chemistry-tutor', 'Explains reactions, mechanisms, equations, and lab concepts.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Biology Tutor', 'biology-tutor', 'Breaks down biology topics with diagrams, definitions, and processes.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Econ Problem Solver', 'econ-problem-solver', 'Solves micro/macro problems with diagrams, graphs, and reasoning steps.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Statistics Helper', 'statistics-helper', 'Explains stats, distributions, tests, and solves calculations.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Probability Explainer', 'probability-explainer', 'Teaches probability concepts using examples and visual reasoning.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Quiz Generator', 'quiz-generator', 'Creates quizzes from readings or topics with multiple difficulty levels.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('SAT/ACT Prep Agent', 'test-prep-agent', 'Generates test practice, strategies, and timing drills.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Classroom Lesson Planner', 'lesson-planner', 'Builds lessons for teachers with objectives, materials, and activities.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Lab Report Helper', 'lab-report-agent', 'Creates lab report outlines, hypotheses, analysis, and error discussion.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Skill Breakdown Agent', 'skill-breakdown-agent', 'Turns a skill (coding, drawing, etc.) into a step-by-step mastery roadmap.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Learning Style Optimizer', 'learning-style-agent', 'Builds study plans based on users cognitive preferences.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Equation Solver', 'equation-solver', 'Solves algebraic, differential, and symbolic equations.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Memory Retention Agent', 'memory-retention-agent', 'Suggests memory techniques and spaced review schedules.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Language Learning Coach', 'language-learning-coach', 'Builds custom language-learning pathways with exercises.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Reading Comprehension Agent', 'reading-comp-agent', 'Generates comprehension questions and summaries for readings.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Paper Structuring Agent', 'paper-structuring-agent', 'Creates outlines and logical flow for academic papers.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Logic Trainer', 'logic-trainer', 'Teaches logical reasoning, fallacies, and LSAT-style problems.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Proof Checker', 'proof-checker', 'Verifies mathematical proofs step-by-step.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Mindmap Generator', 'mindmap-generator', 'Creates visual-style mindmaps from topics, showing hierarchies and sub-topics.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Group Presentation Organizer', 'group-presentation-agent', 'Splits responsibilities + slide structure for group projects.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Homework Helper', 'homework-helper', 'Gives short, direct answers and breakdowns for homework questions across subjects.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Scholarship/Fellowship Agent', 'scholarship-agent', 'Finds scholarships/fellowships and generates tailored applications, essays, timelines, and checklists.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Flashcard Generator', 'flashcard-generator', 'Converts study material into spaced repetition flashcards with Q/A pairings.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Exam Panic Coach', 'exam-panic-coach', 'Gives rapid calming + last-minute study strategies.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Academic Example Finder', 'example-finder', 'Provides relevant examples, case studies, or data for essays.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Text Condenser', 'text-condenser', 'Condenses dense academic writing into simpler forms without losing meaning.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Research Topic Generator', 'research-topic-generator', 'Suggests research topics with rationale, sources, and angles of exploration.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Note Cleaner', 'note-cleaner', 'Converts messy notes into clean, organized, structured documentation.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Research Assistant', 'research-assistant', 'Helps find sources, generate research questions, and structure papers.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Idea-to-Paper Agent', 'idea-to-paper', 'Converts a raw idea into a structured essay or research plan.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Quick Math Solver', 'quick-math-solver', 'Instantly solves simple arithmetic problems with explanations.', 'EDUCATION', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  status = EXCLUDED.status,
  invocation_type = EXCLUDED.invocation_type,
  invocation_config = EXCLUDED.invocation_config,
  updated_at = NOW();

-- ============================================================================
-- PRODUCTIVITY AGENTS
-- ============================================================================

INSERT INTO agents (name, slug, description, domain, status, invocation_type, invocation_config)
VALUES
  ('Personal Board of Advisors Agent', 'pb-advisor-agent', 'Acts as a simulated board to evaluate decisions.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Smart To-Do List Agent', 'smart-todo-agent', 'Creates and prioritizes an adaptive smart to-do list.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Break Reminder Agent', 'break-reminder-agent', 'Suggests optimal break points during study/work.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Life Admin Agent', 'life-admin-agent', 'Helps complete life admin tasks like scheduling, budgeting, and planning.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Task Breakdown Agent', 'task-breakdown', 'Breaks large tasks into granular subtasks with estimated effort and sequencing.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Time Estimator', 'time-estimator', 'Estimates realistic time to complete tasks based on difficulty and user history.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('To-Do List Generator', 'todo-generator', 'Turns inputs into prioritized to-do lists with task grouping and deadlines.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Productivity Timer', 'productivity-timer', 'Generates custom Pomodoro cycles based on task type and mental stamina.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Focus Timer Agent', 'focus-timer-agent', 'Runs customizable Pomodoro or deep-work timers.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Quick Decision Agent', 'quick-decision-agent', 'Helps make fast decisions using pros/cons + gut checks.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Priority Ranking Agent', 'priority-ranking-agent', 'Sorts tasks by urgency, importance, and long-term value.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Project Scope Analyzer', 'project-scope-analyzer', 'Determines scope, risks, and steps for any project.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Weekend Productivity Coach', 'weekend-productivity-agent', 'Designs balanced weekend plans: productivity + rest.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Late-Night Motivation Agent', 'latenight-motivation-agent', 'Helps users push through late-night tasks.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('WFH Workspace Planner', 'workspace-planner-agent', 'Designs ergonomic home office layouts.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Meeting Summary Agent', 'meeting-summary-agent', 'Summarizes meetings into actionables.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Meeting Agenda Builder', 'meeting-agenda-builder', 'Creates structured meeting agendas with timelines.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Meeting Notes Agent', 'meeting-notes-agent', 'Transforms transcripts into structured meeting notes with actions, owners, and deadlines.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Daily Schedule Builder', 'daily-schedule-builder', 'Creates optimized daily routines balancing work, school, meals, breaks, and personal goals.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Calendar Sync Agent', 'calendar-sync-agent', 'Helps convert messy plans into structured calendar events with reminders.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Weekly Planner', 'weekly-planner', 'Creates structured weekly plans balancing academics, workouts, social time, and deep work blocks.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Time Block Planner', 'timeblock-planner', 'Divides a users day into focused time blocks based on priorities.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Project Planner', 'project-planner', 'Breaks large projects into actionable tasks with timelines, milestones, and dependency chains.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Productivity System Designer', 'productivity-system-agent', 'Builds GTD, PARA, or custom systems.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Productivity Workflow Designer', 'workflow-designer', 'Designs custom workflows with triggers, batching, and automation logic.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Optimization Coach', 'optimization-coach', 'Helps optimize systems, routines, workflows using constraints and goals.', 'PRODUCTIVITY', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  status = EXCLUDED.status,
  invocation_type = EXCLUDED.invocation_type,
  invocation_config = EXCLUDED.invocation_config,
  updated_at = NOW();

-- ============================================================================
-- BUSINESS AGENTS
-- ============================================================================

INSERT INTO agents (name, slug, description, domain, status, invocation_type, invocation_config)
VALUES
  ('Analytical Framework Generator', 'framework-generator', 'Gives frameworks like SWOT, PESTLE, 5 Forces, TAM.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Cold Email Writer', 'cold-email-writer', 'Writes high-conversion cold emails tailored to target personas.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Pitch Deck Reviewer', 'pitchdeck-reviewer', 'Gives structured feedback on pitch decks (story, flow, metrics).', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Founder Coach', 'founder-coach', 'Provides advice on leadership, execution, prioritization, and startup psychology.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Startup Idea Generator', 'startup-idea-generator', 'Produces startup ideas with problem statements, users, and GTM strategy.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Pricing Strategy Agent', 'pricing-agent', 'Suggests pricing models (SaaS, freemium, tiered) based on value + competition.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('OKR Generator', 'okr-generator', 'Builds Objectives & Key Results for teams or individuals.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Fundraising Advisor', 'fundraising-advisor', 'Gives tactics on fundraising, investor targeting, pitch structure.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Profitability Analyst', 'profitability-analyst', 'Analyzes cost structure, margins, and ways to improve profitability.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Market Research Agent', 'market-research-agent', 'Produces market landscapes and competitor analysis.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('SWOT Generator', 'swot-generator', 'Creates SWOT analysis with actionable interpretations.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('TAM/SAM/SOM Calculator', 'tamsam-calculator', 'Calculates market size using logical assumptions.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Risk Assessment Agent', 'risk-assessment-agent', 'Identifies risks in plans and gives mitigation strategies.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Project Manager Agent', 'project-manager-agent', 'Builds Gantt-style plans and manages task dependencies.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Business Plan Generator', 'business-plan-generator', 'Creates business plans with financial projections and GTM.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Investor Matching Agent', 'investor-matching', 'Recommends investors based on stage, industry, and thesis.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Exit Strategy Planner', 'exit-strategy-planner', 'Outlines acquisition or IPO pathways with requirements.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Board Meeting Prep Agent', 'board-prep-agent', 'Prepares summaries, risks, and discussion points for board meetings.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Email Follow-Up Generator', 'followup-generator', 'Generates follow-up sequences for outreach campaigns.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Investor Update Writer', 'investor-update-writer', 'Drafts monthly/quarterly investor updates.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Business Case Generator', 'business-case-generator', 'Builds business cases with ROI, assumptions, and metrics.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Cold Email Creator', 'coldemail-agent', 'Generates effective cold emails for outreach.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Funnel Optimization Agent', 'funnel-optimizer', 'Evaluates funnel stages and suggests fixes.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('KPI Tracking Agent', 'kpi-tracker-agent', 'Suggests relevant KPIs for projects.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Hiring Scorecard Agent', 'hiring-scorecard-agent', 'Helps write role scorecards and evaluate candidates.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Startup Equity Split Advisor', 'equity-split-agent', 'Provides frameworks for fair equity splits.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Risk Management Advisor', 'risk-advisor-agent', 'Identifies project risks + mitigation.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Pitch Deck Writer Agent', 'pitchdeck-writer-agent', 'Creates slide outlines for pitch decks.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Business Name Generator', 'bizname-gen-agent', 'Suggests available business names with vibes.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Startup Roadmap Agent', 'startup-roadmap-agent', 'Creates multi-phase roadmaps.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Startup Red Flag Detector', 'startup-redflag-agent', 'Detects risk patterns in early startups.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Funding Strategy Planner', 'funding-strategy-agent', 'Suggests funding routes (bootstrapping, angels, VC).', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Angel Investor Pitch Coach', 'angel-pitch-agent', 'Helps prepare brief, compelling angel pitches.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Social Proof Generator', 'socialproof-agent', 'Helps generate testimonials and proof formats.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Retention Strategy Agent', 'retention-strategy-agent', 'Suggests features and strategies to improve user retention.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Churn Reduction Agent', 'churn-agent', 'Suggests retention strategies for SaaS.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Pricing Strategy Agent', 'pricing-strategy-agent', 'Helps design pricing tiers and models.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Revenue Forecast Agent', 'revenue-forecast-agent', 'Predicts revenue based on inputs, assumptions, and market motion.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Competitor Analysis Agent', 'competitor-research-agent', 'Breaks down competitors using SWOT + positioning.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Market Sizing Agent', 'market-size-agent', 'Generates TAM/SAM/SOM calculations.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Business Model Designer', 'bizmodel-agent', 'Creates business model canvases.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Market Research Collector', 'market-research-collector', 'Gathers and summarizes market insights.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Customer Support Script Agent', 'support-script-agent', 'Generates customer service scripts for tricky interactions.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Startup Strategy Coach', 'startup-strategy-agent', 'Provides structured startup strategy insights.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Go-To-Market Planner', 'gtm-planner-agent', 'Builds GTM strategies with channels + timelines.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Product Requirements Writer', 'prd-writer-agent', 'Writes PRDs with clear user stories + acceptance criteria.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Idea Validator', 'idea-validator', 'Tests ideas using frameworks like SWOT, PMF likelihood, TAM/SAM/SOM.', 'BUSINESS', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  status = EXCLUDED.status,
  invocation_type = EXCLUDED.invocation_type,
  invocation_config = EXCLUDED.invocation_config,
  updated_at = NOW();

-- ============================================================================
-- CAREER AGENTS
-- ============================================================================

INSERT INTO agents (name, slug, description, domain, status, invocation_type, invocation_config)
VALUES
  ('Resume Bullet Rewriter', 'resume-bullet-rewriter', 'Rewrites bullets to be metric-driven and recruiter-friendly.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Career Pivot Strategist', 'career-pivot-agent', 'Designs stepwise plans for switching industries.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Negotiation Script Builder', 'negotiation-script', 'Crafts negotiation scripts for salary, rent, jobs, partnerships.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Resume ATS Optimizer', 'resume-ats-optimizer', 'Optimizes resumes for applicant tracking systems.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Cover Letter Generator', 'coverletter-generator', 'Writes cover letters tailored to roles and company culture.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Salary Benchmark Agent', 'salary-benchmark-agent', 'Compares salaries for roles across industries and regions.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Interview Question Generator', 'interview-q-generator', 'Generates interview questions tailored to job roles and experience levels.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Interview Answer Coach', 'interview-answer-coach', 'Helps users craft strong interview answers using STAR or CAR formats.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Career Roadmap Agent', 'career-roadmap', 'Crafts 1-5 year career roadmaps with required skills, experience gaps, and step-by-step progression plans.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Job Search Strategist', 'jobsearch-strategist', 'Designs job search strategies tailored to skill set and industry.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Leadership Style Analyzer', 'leadership-analyzer', 'Assesses leadership style and recommends improvement strategies.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Hiring Outreach Agent', 'hiring-outreach-agent', 'Generates cold messages to talent.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Career Skill Matcher', 'skill-matcher', 'Matches skills to career paths with required competencies.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Mentorship Script Agent', 'mentor-script-agent', 'Generates questions for mentor meetings.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Internship Requirement Checker', 'internship-req-checker', 'Explains requirements and expectations for internships.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Interview Practice Coach', 'interview-coach-agent', 'Simulates interview questions with feedback.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Resume Builder', 'resume-agent', 'Generates polished resumes tailored to job descriptions, with bullet improvements and formatting guidance.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb),
  ('Tactical Negotiator', 'tactical-negotiator', 'Gives tactical scripts and strategies to negotiate salary, rent, deals, and interpersonal conflicts.', 'CAREER', 'EXPERIMENTAL', 'INTERNAL_FUNCTION', '{"function_name": "experimental-agent", "endpoint": "/functions/v1/experimental-agent", "method": "POST"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  status = EXCLUDED.status,
  invocation_type = EXCLUDED.invocation_type,
  invocation_config = EXCLUDED.invocation_config,
  updated_at = NOW();

SELECT 'Part 3 complete: EDUCATION, PRODUCTIVITY, BUSINESS, CAREER agents inserted' as status;

